import type { Metadata } from "next";
import "./globals.scss";
import { Roboto_Condensed, Roboto_Flex } from "@next/font/google";
import Header from "@/components/header/Header";
import SideBar from "@/components/sideBar/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoFlex = Roboto_Flex({
    subsets: ['latin', 'cyrillic'],
    weight: ['400', '500', '600', '700'],
    style: ['normal'],
  })

const robotoCondensed = Roboto_Condensed({
    subsets: ['latin', 'cyrillic'],
    weight: ['400', '500', '600', '700'],
    style: ['normal'],
  })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFlex.className} antialiased`}
      >
        <Header/>
        <main>
          <SideBar/>
          {children}
        </main>
      </body>
    </html>
  );
}
