import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "@next/font/google";
import Header from "@/components/header/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
    subsets: ['latin', 'cyrillic'],
    weight: ['400', '700'],
    style: ['normal', 'italic'],
  })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
